name: Automated tests

on: 
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Mozila
        run: whichis firefox
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install Firefox
        run: |
          sudo apt-get install firefox
          sudo chmod +x /usr/bin/firefox
      - name: Check Mozila
        run: whichis firefox
      - name: Install Edge
        run: sudo apt-get install microsoft-edge-stable
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest