name: Automated tests

on: 
  workflow_dispatch:
    inputs:
      deployment_target:
        description: 'Choose target'
        required: true
        default: all_browsers
        type: choice
        options:
          - all_browsers
          - chrome_only
          - firefox_only
          - edge_only

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Mozila
        run: whereis firefox
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install Edge
        run: sudo apt-get install microsoft-edge-stable
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: All browsers
        if: "github.event.inputs.deployment_target == 'all_browsers'"
        run: pytest
      - name: Only Chrome
        if: "github.event.inputs.deployment_target == 'chrome_only'"
        run: pytest -v -k 'chrome'
      - name: Only Firefox
        if: "github.event.inputs.deployment_target == 'firefox_only'"
        run: pytest -v -k 'firefox'
      - name: Only Edge
        if: "github.event.inputs.deployment_target == 'edge_only'"
        run: pytest -v -k 'edge'