name: Automated tests

on: 
  workflow_dispatch:
    inputs:
      deployment_target:
        description: 'Choose target'
        required: true
        default: 'All browsers'
        type: choice
        options:
          - 'All browsers'
          - 'Only Chrome'
          - 'Only Firefox'
          - 'Only Edge'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Mozila
        run: whereis firefox
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install Edge
        run: sudo apt-get install microsoft-edge-stable
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: All browsers
        if: "github.events.inputs.deployment_target == 'All browsers'"
        run: pytest
      - name: Only Chrome
        if: "github.events.inputs.deployment_target == 'Only Chrome'"
        run: pytest -v -k 'chrome'
      - name: Only Firefox
        if: "github.events.inputs.deployment_target == 'Only Firefox'"
        run: pytest -v -k 'firefox'
      - name: Only Edge
        if: "github.events.inputs.deployment_target == 'Only Edge'"
        run: pytest -v -k 'edge'